#include "PlanetConstant.h"
int PlanetConstant::groupNumber=15;
int PlanetConstant::oneGroupNumber=20;
float PlanetConstant::lineWidth=8.0f;
int PlanetConstant::paiNumber=groupNumber*oneGroupNumber;
float PlanetConstant::perAngle=0;
float PlanetConstant::rotateAngle=0;
float PlanetConstant::distanceDai=8.162f;
float PlanetConstant::distanceDaiBig=22.0f;
float PlanetConstant::linWidthSpan=lineWidth/oneGroupNumber;
float PlanetConstant::angleSpan=360.0f/groupNumber;